name = "TargeneCore"
uuid = "3aa9512e-41c2-4133-bfaa-ba71048dd391"
authors = ["olivierlabayle"]
version = "0.9.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BGEN = "6db4b851-9beb-4b83-9d64-eb1cfb37721d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SnpArrays = "4e780e97-f5bf-4111-9dc4-b70aaf691b06"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TMLE = "8afdd2fb-6e73-43df-8b62-b1650cd9c8cf"
TMLECLI = "2573d147-4098-46ba-9db2-8608d210ccac"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgParse = "1.1"
Arrow = "2.7.0"
BGEN = "0.2.1"
CSV = "0.9, 0.10"
CairoMakie = "0.12"
CategoricalArrays = "0.10"
Combinatorics = "1.0"
DataFrames = "1.2"
OrderedCollections = "1.6.3"
PackageCompiler = "2.1.17"
SnpArrays = "0.3"
StableRNGs = "1.0.1"
Statistics = "1.10"
TMLE = "0.17"
MKL = "0.7"
YAML = "0.4.9"
julia = "1.10, 1"
